import { Concept } from "./types";

/** v1.1 dictionary: tighter matchers (require a tech anchor) + broader coverage (~36 concepts). */
export const CONCEPTS: Concept[] = [
  { id: "git-commit", label: "Git commit", category: "git",
    matchers: [/git\s+commit/i, /\bcommit(ted|s|ting)?\b.{0,30}\b(branch|repo|stage|change|git|main)/i, /\b(make|create|new)\s+a?\s*commit\b/i] },
  { id: "git-branch", label: "Git branch", category: "git",
    matchers: [/git\s+branch/i, /\bbranch(es|ing)?\b.{0,30}\b(git|commit|merge|repo|main|master|checkout)/i, /\b(checkout|switch\s+to)\b.{0,12}branch/i] },
  { id: "git-push", label: "Git push", category: "git",
    matchers: [/git\s+push/i, /\bpush(ed|ing)?\b.{0,20}\b(origin|remote|branch|repo)/i] },
  { id: "git-merge", label: "Git merge", category: "git",
    matchers: [/git\s+merge/i, /\bmerge\s+conflict/i, /\bmerg(e|ed|ing)\b.{0,20}\bbranch/i] },
  { id: "git-pull", label: "Git pull", category: "git",
    matchers: [/git\s+pull/i, /\bpull(ed|ing)?\b.{0,20}\b(origin|remote|latest|changes)/i] },
  { id: "repository", label: "Code repository", category: "git",
    matchers: [/\brepository\b/i, /\brepo\b/i, /\bgit\s+repo/i] },
  { id: "pull-request", label: "Pull request", category: "git",
    matchers: [/\bpull\s+request/i, /\bPR\b.{0,15}\b(merge|review|open|branch)/i] },
  { id: "git-diff", label: "Code diff", category: "git",
    matchers: [/git\s+diff/i, /\bdiff\b.{0,20}\b(commit|branch|change|file)/i] },
  { id: "npm-install", label: "Installing packages (npm)", category: "node",
    matchers: [/npm\s+install/i, /\bnode_modules\b/, /\byarn\s+add\b/i, /\bpnpm\s+(install|add)/i] },
  { id: "npm-script", label: "npm scripts", category: "node",
    matchers: [/npm\s+run\b/i, /\bpackage\.json\b.{0,20}\bscripts/i] },
  { id: "dependency", label: "Dependency", category: "node",
    matchers: [/\bdependenc(y|ies)\b/i, /\bdevDependencies\b/] },
  { id: "env-var", label: "Environment variable", category: "shell",
    matchers: [/\benvironment\s+variable/i, /\bprocess\.env\b/, /\b\.env\b/, /\benv\s+var/i] },
  { id: "cli", label: "Command-line interface (CLI)", category: "shell",
    matchers: [/\bcommand[- ]line/i, /\bCLI\b/, /\bterminal\s+command/i] },
  { id: "shell-script", label: "Shell script", category: "shell",
    matchers: [/\bshell\s+script/i, /\bbash\s+script/i, /\.sh\b/] },
  { id: "ssh", label: "SSH / secure shell", category: "shell",
    matchers: [/\bssh\b/i, /\bSSH\s+key/i] },
  { id: "api", label: "API", category: "web",
    matchers: [/\bAPI\b.{0,25}\b(call|request|endpoint|key|response|REST)/i, /\bREST\s+API/i, /\bendpoint\b/i] },
  { id: "http-status", label: "HTTP status code", category: "web",
    matchers: [/\bHTTP\b.{0,8}\b\d{3}\b/i, /\bstatus\s+code\b/i, /\b(404|500|403|401)\b.{0,15}\b(error|not\s+found|server|unauthorized|forbidden)/i] },
  { id: "http-request", label: "HTTP request", category: "web",
    matchers: [/\bHTTP\s+request/i, /\b(GET|POST|PUT|DELETE)\b.{0,15}\b(request|endpoint|api|route)/i] },
  { id: "webhook", label: "Webhook", category: "web",
    matchers: [/\bwebhook/i] },
  { id: "port", label: "Network port", category: "web",
    matchers: [/\bport\s+\d{2,5}\b/i, /\blocalhost:\d+/i] },
  { id: "localhost", label: "localhost", category: "web",
    matchers: [/\blocalhost\b/i, /\b127\.0\.0\.1\b/] },
  { id: "json", label: "JSON", category: "data",
    matchers: [/\bJSON\b/, /\.json\b/] },
  { id: "database", label: "Database", category: "data",
    matchers: [/\bdatabase\b/i, /\bSQL\b/, /\bquery\b.{0,20}\b(table|database|row|select)/i] },
  { id: "schema", label: "Data schema", category: "data",
    matchers: [/\bschema\b/i] },
  { id: "docker", label: "Docker container", category: "devops",
    matchers: [/\bDocker\b/, /\bcontainer\b.{0,20}\b(docker|image|run|build)/i, /\bDockerfile\b/] },
  { id: "deploy", label: "Deploying", category: "devops",
    matchers: [/\bdeploy(ed|ing|ment)?\b/i, /\bproduction\s+server/i] },
  { id: "ci", label: "Continuous Integration (CI)", category: "devops",
    matchers: [/\bCI\b.{0,15}\b(pipeline|build|run|workflow|test)/i, /\bGitHub\s+Actions/i, /\bcontinuous\s+integration/i] },
  { id: "compile", label: "Compiling code", category: "build",
    matchers: [/\bcompil(e|ed|ing|ation)\b/i, /\btsc\b/, /\bTypeScript\b.{0,20}\b(compile|build)/i] },
  { id: "build-tool", label: "Build / bundling", category: "build",
    matchers: [/\bbundl(e|er|ing)\b/i, /\bbuild\s+step/i, /\bwebpack\b|\bvite\b|\besbuild\b/i] },
  { id: "test-suite", label: "Automated tests", category: "testing",
    matchers: [/\btest\s+suite/i, /\b(tests?)\b.{0,15}\b(pass(ed|ing)?|fail(ed|ing)?)/i, /\bvitest\b|\bpytest\b|\bjest\b/i] },
  { id: "function", label: "Function", category: "programming",
    matchers: [/\bfunction\b.{0,25}\b(call|return|parameter|argument|define|javascript|code|method)/i, /\b(JavaScript|TypeScript|Python)\s+function/i] },
  { id: "async", label: "Asynchronous code", category: "programming",
    matchers: [/\basync\b/i, /\bawait\b/i, /\bpromise\b.{0,20}\b(resolve|reject|async|await|then)/i] },
  { id: "regex", label: "Regular expression", category: "programming",
    matchers: [/\bregex\b/i, /\bregular\s+expression/i] },
  { id: "type-system", label: "Types / type checking", category: "programming",
    matchers: [/\btype\s+(error|check|annotation|definition)/i, /\bTypeScript\s+types?/i] },
  { id: "stack-trace", label: "Stack trace / error log", category: "programming",
    matchers: [/\bstack\s+trace/i, /\btraceback\b/i] },
  { id: "package-manager", label: "Package manager", category: "node",
    matchers: [/\bpackage\s+manager/i, /\bnpm\b.{0,15}\bregistry/i] },
];
