import { Concept } from "./types";

/** v1 starter dictionary. Add more entries following the same shape. */
export const CONCEPTS: Concept[] = [
  { id: "git-commit", label: "Git commit", category: "git",
    matchers: [/\bcommit\b/i, /git\s+commit/i] },
  { id: "git-branch", label: "Git branch", category: "git",
    matchers: [/\bbranch\b/i, /git\s+branch/i] },
  { id: "git-push", label: "Git push", category: "git",
    matchers: [/git\s+push/i, "pushed to origin"] },
  { id: "git-merge", label: "Git merge", category: "git",
    matchers: [/git\s+merge/i, "merge conflict"] },
  { id: "npm-install", label: "Installing packages (npm)", category: "node",
    matchers: [/npm\s+install/i, "node_modules"] },
  { id: "npm-script", label: "npm scripts", category: "node",
    matchers: [/npm\s+run/i, "package.json scripts"] },
  { id: "env-var", label: "Environment variable", category: "shell",
    matchers: ["environment variable", /\benv\b/i, "process.env"] },
  { id: "api", label: "API", category: "web",
    matchers: [/\bAPI\b/, /\bendpoint\b/i, "REST"] },
  { id: "json", label: "JSON", category: "data",
    matchers: ["JSON", /\.json\b/] },
  { id: "docker", label: "Docker container", category: "devops",
    matchers: ["Docker", /\bcontainer\b/i, "Dockerfile"] },
  { id: "test-suite", label: "Automated tests", category: "testing",
    matchers: ["test suite", "passing", "failing test", /\bvitest\b/i, /\bpytest\b/i] },
  { id: "dependency", label: "Dependency", category: "node",
    matchers: [/\bdependency\b/i, /\bdependencies\b/i, "devDependencies"] },
  { id: "compile", label: "Compiling code", category: "build",
    matchers: [/\bcompile\b/i, /\bcompiled\b/i, "TypeScript", "tsc"] },
  { id: "http-status", label: "HTTP status code", category: "web",
    matchers: [/\b(200|404|500)\b/, "status code"] },
  { id: "cli", label: "Command-line interface (CLI)", category: "shell",
    matchers: ["command line", "CLI", "terminal command"] },
  { id: "regex", label: "Regular expression", category: "programming",
    matchers: ["regex", "regular expression"] },
  { id: "async", label: "Asynchronous code", category: "programming",
    matchers: [/\basync\b/i, /\bawait\b/i, /\bpromise\b/i] },
  { id: "function", label: "Function", category: "programming",
    matchers: [/\bfunction\b/i, /\bparameter\b/i, "return value"] },
  { id: "repository", label: "Code repository", category: "git",
    matchers: [/\brepository\b/i, /\brepo\b/i] },
  { id: "webhook", label: "Webhook", category: "web",
    matchers: ["webhook"] },
];
