export * from "./types";
export { CONCEPTS } from "./concepts";
export { detectConcepts } from "./detector";
export { scoreConcepts } from "./detector";
export { scoreSignals } from "./detector";
export { resolveConcept } from "./detector";
export { suggestConcepts } from "./detector";
export { conceptsFromSignals } from "./signals";
export type { ScoredConcept, ConceptSuggestion } from "./detector";
export { topicCategories, topicsInCategory, categoryLabel, relatedConcepts } from "./topics";
export type { TopicCategory, TopicConcept } from "./topics";
export { InMemoryProfile, JsonFileProfile } from "./profile";
export { InMemoryCache, JsonFileCache } from "./cache";
export { MockGenerator, CliGenerator, ClaudeCliGenerator, CodexCliGenerator, GeminiCliGenerator, FallbackGenerator, buildLessonPrompt, parseLessonJson } from "./generator";
export type { ArgsBuilder } from "./generator";
export { Lumi, LumiOptions } from "./lumi";
export { levelFromCount } from "./level";
export { extractLatestAssistantText } from "./transcript";
export { extractSignals } from "./transcript";
export { lumiHome, profilePath, cachePath, feedPath } from "./paths";
export { renderGlossary } from "./glossary";
export { reviewIntervalDays, dueForReview, recallQuestion } from "./review";
export { runCli, readStdin, generatorForSource } from "./cli";
export { lessonEvent, appendEvent, readEventsSince, dedupeById, lessonFromEvent } from "./feed";
export type { FeedEvent, FeedLesson } from "./feed";
export { welcomeMessage, milestoneFor, progressMessage, nextMilestone } from "./milestones";
export type { NextMilestone } from "./milestones";
export { createOverlayServer } from "./server";
export type { OverlayServerDeps } from "./server";
export { OVERLAY_HTML } from "./overlay";
export { startServer } from "./cli";
export { doctorReport } from "./doctor";
export type { DoctorInput } from "./doctor";
export { atomicWriteFileSync } from "./fsutil";
export { dailyGoalStatus, streakWithFreeze, earnedBadges, nextBadge, JsonFileHabitStore } from "./habit";
export type { HabitState, DailyGoalStatus, StreakWithFreezeResult, Badge, NextBadge } from "./habit";
export { learningStats } from "./stats";
export type { LearningStats, CategoryStat, RecentStat } from "./stats";
export { buildAdvicePrompt, offlineAdvice, runAdvise, CliAdviceGenerator, ClaudeAdviceGenerator } from "./advise";
export type { AdviceInput, AdviceGenerator, RunAdviseDeps } from "./advise";
export { buildPolishPrompt, offlinePolish, CliPolisher, ClaudePolisher, FallbackPolisher, runPrompt } from "./prompt";
export type { PromptPolisher, PolishOpts } from "./prompt";
export { resolveTextModel, runTextModel } from "./textmodel";
export type { TextModelSpec } from "./textmodel";
export { detectInstalledTools, mergeCodexNotify, mergeCursorHook, mergeCopilotHook, mergeGeminiHook, buildCopilotHooksJson, runSetup } from "./setup";
export type { SetupDeps, MergeResult } from "./setup";
export { listPaths, pathProgress, allPathsProgress, nextAcrossPaths } from "./curriculum";
export type { Path, PathProgress } from "./curriculum";
export { renderProgressCard, progressCardFromProfile } from "./card";
export type { ProgressCardInput, ProgressCardFromProfileOpts } from "./card";
export { detectRisks, riskLessonHint, riskAdvice, riskFix, severityLabel, SECURITY_CONCEPT_IDS } from "./risk";
export type { RiskHit } from "./risk";
export { weeklyDigest, renderDigestText, renderDigestHtml } from "./digest";
export type { Digest } from "./digest";
export { renderCertificate, certificateFromProfile, isCertificateEligible } from "./certificate";
export type { CertificateInput } from "./certificate";
export { detectStuck, unstuckAdvice } from "./unstuck";
export type { StuckSignal } from "./unstuck";
export { quickCheckPrompt } from "./quickcheck";
export { learnMoreUrl } from "./learnmore";
export { exportBundle, importBundle, mergeProfiles, mergeHabit } from "./portability";
export type { LumiBundle, ImportResult } from "./portability";
export { onboardingGuide } from "./onboarding";
export { auditRisks, gradeFor } from "./audit";
export type { AuditReport, AuditGrade } from "./audit";
export { auditPath } from "./scan";
export type { ProjectAuditReport, FileFinding } from "./scan";
export { verifyLicense, JsonFileLicenseStore, currentEntitlement } from "./license";
export type { LicenseResult, CurrentEntitlementOpts } from "./license";
export { PRO_FEATURES, isPro, requiresPro, allowed, upgradeMessage } from "./entitlements";
export type { Feature } from "./entitlements";
