#!/usr/bin/env node
/**
 * sign-license.mjs
 *
 * Issues a Lumi Pro license key for a given email address.
 *
 * Usage:
 *   node core/scripts/sign-license.mjs \
 *     --key ./lumi-license-private.pem \
 *     --email user@example.com \
 *     [--expires 2026-12-31]
 *
 * Options:
 *   --key      Path to the private key PEM file (generated by make-license-keypair.mjs)
 *   --email    The customer's email address (ties the license to them)
 *   --expires  Optional ISO date (YYYY-MM-DD) after which the key stops working
 *
 * Output:
 *   Prints the license key string to stdout. Give this to the customer.
 *   They activate it by running `lumi license <key>`.
 *
 * Example (no expiry — perpetual license):
 *   node core/scripts/sign-license.mjs \
 *     --key ./lumi-license-private.pem \
 *     --email alice@example.com
 *
 * Example (1-year subscription):
 *   node core/scripts/sign-license.mjs \
 *     --key ./lumi-license-private.pem \
 *     --email alice@example.com \
 *     --expires 2027-06-16
 */

import { readFileSync } from "node:fs";
import { sign } from "node:crypto";

// ---------------------------------------------------------------------------
// Argument parsing (no external deps)
// ---------------------------------------------------------------------------

const args = process.argv.slice(2);

function getArg(name) {
  const idx = args.indexOf(name);
  if (idx === -1 || idx + 1 >= args.length) return undefined;
  return args[idx + 1];
}

const keyFile = getArg("--key");
const email = getArg("--email");
const expires = getArg("--expires");

if (!keyFile || !email) {
  console.error("Usage: node sign-license.mjs --key <private.pem> --email <email> [--expires YYYY-MM-DD]");
  process.exit(1);
}

// Validate email loosely
if (!email.includes("@")) {
  console.error(`Error: "${email}" does not look like a valid email address.`);
  process.exit(1);
}

// Validate expires if provided
if (expires) {
  const d = new Date(expires);
  if (isNaN(d.getTime())) {
    console.error(`Error: --expires "${expires}" is not a valid date. Use YYYY-MM-DD format.`);
    process.exit(1);
  }
  if (d <= new Date()) {
    console.error(`Warning: --expires "${expires}" is already in the past. The key will be immediately invalid.`);
    // Continue anyway — maybe the caller intended a backdated key for testing.
  }
}

// ---------------------------------------------------------------------------
// Load private key
// ---------------------------------------------------------------------------

let privateKeyPem;
try {
  privateKeyPem = readFileSync(keyFile, "utf8");
} catch (err) {
  console.error(`Error: Could not read private key file "${keyFile}": ${err.message}`);
  process.exit(1);
}

// ---------------------------------------------------------------------------
// Build payload and sign
// ---------------------------------------------------------------------------

function b64urlEncode(str) {
  return Buffer.from(str, "utf8")
    .toString("base64")
    .replace(/\+/g, "-")
    .replace(/\//g, "_")
    .replace(/=/g, "");
}

const payload = {
  email,
  tier: "pro",
  issued: new Date().toISOString(),
  ...(expires ? { expires: new Date(expires).toISOString() } : {}),
};

const payloadB64 = b64urlEncode(JSON.stringify(payload));

let sigBuffer;
try {
  // Ed25519 one-shot sign: sign(null, data, privateKey)
  sigBuffer = sign(null, Buffer.from(payloadB64, "utf8"), privateKeyPem);
} catch (err) {
  console.error(`Error: Signing failed. Is "${keyFile}" a valid Ed25519 private key PEM? ${err.message}`);
  process.exit(1);
}

const sigB64 = sigBuffer
  .toString("base64")
  .replace(/\+/g, "-")
  .replace(/\//g, "_")
  .replace(/=/g, "");

const licenseKey = `${payloadB64}.${sigB64}`;

// ---------------------------------------------------------------------------
// Output
// ---------------------------------------------------------------------------

console.log("=".repeat(60));
console.log("LUMI PRO LICENSE KEY");
console.log("=".repeat(60));
console.log();
console.log(`Email:   ${email}`);
console.log(`Issued:  ${payload.issued}`);
if (payload.expires) {
  console.log(`Expires: ${payload.expires}`);
} else {
  console.log("Expires: never (perpetual)");
}
console.log();
console.log("License key (give this to the customer):");
console.log("-".repeat(60));
console.log(licenseKey);
console.log("-".repeat(60));
console.log();
console.log("The customer runs: lumi license <key>");
